# General
gral_prec_file = '/home/rrealrangel/MEGA/proyectos/2019/2019-inv-01_cathments-classification/main/analisys/per_catchment/sg30057/prec_ts_v2.csv'
gral_disc_file = '/home/rrealrangel/MEGA/proyectos/2019/2019-inv-01_cathments-classification/main/analisys/per_catchment/sg30057/disc_ts_v2.csv'
gral_output_dir = '/home/rrealrangel/MEGA/proyectos/2019/2019-inv-01_cathments-classification/main/analisys/per_catchment/sg30057/drgt_assessment/'
gral_show_positives = true

# Drought definition
pooling_method = 'ma'
agg_scale = 15   # Used only if pooling_method == 'ma'
threshold = 'median'

