# General
gral_prec_file = '/home/realrangel/MEGA/projects/2019/2019-01_cathments-classification/main/analisys/catchments/30057_pichucalco/prec_ts_v2.csv'
gral_disc_file = '/home/realrangel/MEGA/projects/2019/2019-01_cathments-classification/main/analisys/catchments/30057_pichucalco/disc_ts_v2.csv'
gral_output_dir = '/home/realrangel/MEGA/projects/2019/2019-inv-01_cathments-classification/main/analisys/catchments/30057_pichucalco/drougt_assessment/'
gral_show_positives = true

# Drought definition
pooling_method = 'ma'
agg_scale = 15   # Used only if pooling_method == 'ma'
threshold = 'median'

